version: '3.8'

networks:
  # internal
  internal:
    internal: true
  # ingress proxy and exposed services
  ingress:
    internal: true
  # egress for containers needing access to external networks
  egress:

services:

  postgres:
    extends:
      file: ${CONFIG_PATH}/docker-compose/base.yml
      service: base
    build: docker/postgres
    networks:
      - internal
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data
      - ${SECRETS_PATH}/postgres:/run/secrets:ro

  pgadmin4:
    extends:
      file: ${CONFIG_PATH}/docker-compose/base.yml
      service: base
    build: docker/pgadmin4
    networks:
      - internal
      - ingress
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_default_password
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_AUTO_DISCOVER_SERVERS=False
    volumes:
      - pgadmin4_data_volume:/var/lib/pgadmin
      - ${SECRETS_PATH}/pgadmin4/pgadmin_default_password:/run/secrets/pgadmin_default_password:ro
      - ${SECRETS_PATH}/postgres/postgres_password:/run/secrets/postgres_password:ro
      - ${CONFIG_PATH}/pgadmin4/servers.json:/pgadmin4/servers.json:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-pgadmin4.entrypoints=https"
      - "traefik.http.routers.traefik-pgadmin4.rule=Host(`pgadmin4.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.traefik-pgadmin4.loadbalancer.server.port=80"

  home-assistant:
    extends:
      file: ${CONFIG_PATH}/docker-compose/base.yml
      service: base
    depends_on:
      - postgres
    build: docker/home-assistant
    networks:
      - internal
      - ingress
      - egress
    volumes:
      - ${DATA_PATH}/home-assistant:/config
      - ${CONFIG_PATH}/home-assistant/configuration.yaml:/config/configuration.yaml:ro
      - ${CONFIG_PATH}/home-assistant/configuration:/config/configuration:ro
      - ${SECRETS_PATH}/home-assistant/secrets.yaml:/config/secrets.yaml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-home-assistant.entrypoints=https"
      - "traefik.http.routers.traefik-home-assistant.rule=Host(`home-assistant.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.traefik-home-assistant.loadbalancer.server.port=8123"

  traefik:
    extends:
      file: ${CONFIG_PATH}/docker-compose/base.yml
      service: base
    build: docker/traefik
    networks:
      - ingress
      - egress
    command:
      - --api=true
      - --api.dashboard=true
      - --api.insecure=true
      - --certificatesResolvers.default.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesResolvers.default.acme.storage=/acme/acme.json
      - --certificatesResolvers.default.acme.httpChallenge.entryPoint=http
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certresolver=default
      - --entrypoints.https.http.tls.domains[0].main=${TRAEFIK_DOMAIN}
      - --entrypoints.https.http.tls.domains[1].main=pgadmin4.${TRAEFIK_DOMAIN}
      - --entrypoints.https.http.tls.domains[2].main=home-assistant.${TRAEFIK_DOMAIN}
      - --global.checkNewVersion=false
      - --global.sendAnonymousUsage=false
      - --log.level=WARN
      - --providers.docker
      - --providers.docker.exposedByDefault=false
    labels:
      - "traefik.enable=true"
      # HTTP-to-HTTPS Redirect
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.routers.http-catchall.service=http-catchall-svc"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.services.http-catchall-svc.loadbalancer.server.port=80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_acme_volume:/acme
      # TODO secure the access
      - /var/run/docker.sock:/var/run/docker.sock

  traefik-whoami:
    extends:
      file: ${CONFIG_PATH}/docker-compose/base.yml
      service: base
    build: docker/traefik-whoami
    networks:
      - ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-whoami.entrypoints=https"
      - "traefik.http.routers.traefik-whoami.rule=Host(`${TRAEFIK_DOMAIN}`)"
      - "traefik.http.services.traefik-whoami.loadbalancer.server.port=80"

  vpn:
    extends:
      file: ${CONFIG_PATH}/docker-compose/base.yml
      service: base
    build: docker/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - INTERNAL_SUBNET=${WIREGUARD_SUBNET}
      - ALLOWEDIPS=${WIREGUARD_ALLOWEDIPS}
    volumes:
      - /lib/modules:/lib/modules
      - ${DATA_PATH}/wireguard:/config
      - ${CONFIG_PATH}/wireguard/peer.conf:/config/templates/peer.conf:ro
      - ${CONFIG_PATH}/wireguard/server.conf:/config/templates/server.conf:ro
    ports:
      - "${WIREGUARD_PUBLIC_PORT}:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  pgadmin4_data_volume:
  traefik_acme_volume:
